### ISSUE TITLE
Possible to replicate this with your Script.

### ISSUE THREAD

**Issue by DeysonOrtiz** [jrue/Vimeo-jQuery-API#17]
Hello and good day.

I had wanted to know if your script can accomplish something like this.  Please note what happens when you hover over the thumbnail and how it unloads and resets when we hover onto another thumbnail:
http://videohive.net/category/stock-footage

I have noticed Jean-Marie has gotten close to what I need here: https://github.com/jrue/Vimeo-jQuery-API/issues/11

I get the missing part would be the play on mouseover and the loading icon.

Thank you for your time and have an amazing day.  :)

**Comment by jrue** [comment]
Sorry for the looong delay. I'm just catching up. Not sure if this is still relevant, but this should work:

```javascript
$("iframe[src*='vimeo.com']").hover(function(){
    $(this).vimeo("play");
}, function(){
    $(this).vimeo("pause");
});
```

This assumes all of the vimeos are statically loaded in the HTML. If you're adding them with JavaScript, you'll need to run a new method I just added called `vimeoLoad()` after you dynamically load each video. I haven't tested the above script, but in general, that's how I would approach it.

Not sure if Vimeo is the best tool for what you're trying to do because you'll see an ugly play button on each video.

**Comment by DeysonOrtiz** [comment]
You are right about the play button.  The reason I use it is because of the quality of video, ease of use and cost.  Once I have more time and higher budget I will look into a fully custom solution. :)  Thank you :)
